apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: newrelic-deployment-hook
build:
  artifacts:
    - image: ghcr.io/faithlife/newrelic-deployment-hook
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
      context: "src/NewRelicDeploymentHook"
deploy:
  kubectl:
    manifests:
      - k8s/webhook-deployment.yaml
      - k8s/webhook-config.yaml
