---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: newrelic-deployment-hook-cfg
  labels:
    app: newrelic-deployment-hook
webhooks:
  - name: newrelic-deployment-hook.faithlife.io
    clientConfig:
      service:
        name: newrelic-deployment-hook-svc
        namespace: default
        path: "/mutate"
      caBundle: $CA_BUNDLE
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector:
      matchLabels:
        newrelic-deployment: enabled
